### ISSUE TITLE
Potion restriction improvements

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/UHC#79]
What we actually want is something better than restricting items that can be placed in the stand overall. 

Having a config file with stuff like:

``` yaml
potions:
  STRENGTH: 
    max tier: 1
  POISON:
    disable splash: true
  INVISIBILITY:
    max tier: 0
```

Defaults being to allow all tiers + splash.

We'd have to look into decent ways of stopping the brewing stand from disallowing the potions while still giving decent feedback to the client. We could potentially inspect the output slots when inserting items and disallow/pop out the affected potions and likewise when inserting potions
